### ISSUE TITLE
_tkinter.TclError: Item  already exists

### ISSUE THREAD

**Issue by jpfaff** [hwstar/BOMtools#2]
When executing partmgr.py I get the following error:

```
Traceback (most recent call last):
  File "./partmgr.py", line 1216, in <module>
    parts.refresh()
  File "./partmgr.py", line 883, in refresh
    self.refresh_default_processor(like)
  File "./partmgr.py", line 847, in refresh_default_processor
    parent_iid = self.ltree.insert("", "end", "", tag=[pn,'partrec'], values=((pn, desc, '', '')))
  File "/usr/lib/python3.6/tkinter/ttk.py", line 1341, in insert
    "-id", iid, *opts)
_tkinter.TclError: Item  already exists
```
I was able to solve it by removing the third argument from all `self.ltree.insert` calls:
example:
` parent_iid = self.ltree.insert("", "end", "", tag=[pn,'partrec'], values=((pn, desc, '', '')))` becomes 
` parent_iid = self.ltree.insert("", "end", tag=[pn,'partrec'], values=((pn, desc, '', '')))`.
I think it is related to following Issue: https://bugs.python.org/issue33096

**Comment by radekska** [comment]
Very helpful! Thanks

**Comment by hwstar** [comment]
@jpfaff Thanks for finding this issue.  I just noticed it myself when I upgraded Linux to a newer version

**Comment by mdramezani** [comment]
Thank you!

**Comment by k34a** [comment]
Thank you very much !

**Comment by mustafatalha** [comment]
Thank you!
